class AppStrings{

  static const String languagejson='{"appname":"UpToFi",'
      '"privacytext":"By continuing you agree that you have read and accept our",'
      '"copyrights":"© 2020 Dr. Khubybe’s Ltd. All rights reserved",'
      '"copyrightslocation":"Made with love in London",'
      '"tellasabout":"Tell us about your interest?",'
      '"emailhint":"E-mail",'
      '"passwordhint":"Password",'
      '"Appname":"UpToDateFi",'
      '"appnamehint":"scientific Research, Truly Up To Date and Simplified",'
      '"loginwithemail":"Login With Email",'
      '"login":"LOGIN",'
      '"loginnow":"LOGIN NOW",'
      '"forgotpassword":"FORGOT PASSWORD ?",'
      '"rights":"© 2020 Dr. Khubybe’s Ltd. All rights reserved",'
      '"rightslocation":"Made with love in London",'
      '"unkownerror":"Some thing went wrong",'
      '"tellusintrest":"Tell us about your interest?",'
      '"Ready":"Ready!",'
      '"startjourney":"Start Your Journey",'
      '"letsstart":"LET\'S START",'
      '"next":"Next",'
      '"Home":"Home",'
      '"Library":"Library",'
      '"Explore":"Explore",'
      '"Repetition":"Repetition",'
      '"Me":"Me",'
      '"whatsnew":"What is new!",'
      '"pickedforyou":"Picked for you!",'
      '"careersuccess":"Career & Success",'
      '"communication":"Communication(Skills)",'
      '"creativity":"Creativity",'
      '"economics":"Economics",'
      '"education":"Education",'
      '"entrepreneurship":"Entrepreneurship",'
      '"happiness":"Happiness",'
      '"innovation":"Innovation",'
      '"leadership":"Leadership",'
      '"management":"Management",'
      '"marketing":"Marketing",'
      '"medical":"Medical",'
      '"mindbrain":"Mind & Brain",'
      '"nature":"Nature & Environment",'
      '"personlGrowth":"Personal Growth & Motivation",'
      '"Politics":"Politics",'
      '"relationship":"Relationship",'
      '"society":"Society & Culture",'
      '"technology":"Technology"'
  '}';



}